import { isApprovedClaim, type ProductClaim } from "./claims.ts";

export type ContentStatus = "draft" | "claim_validation" | "review" | "approved" | "scheduled" | "published" | "failed" | "archived";

export interface ContentDraft {
  id: string;
  organisationId: string;
  channel: "instagram" | "meta_ad" | "website" | "other";
  body: string;
  citedClaimIds: readonly string[];
  status: ContentStatus;
  createdBy: string;
}

export interface ContentValidation {
  valid: boolean;
  reasons: readonly string[];
}

/**
 * Content drafts can only cite currently approved claims. This intentionally
 * validates references, not language generated by an AI: unreferenced factual
 * assertions must be reviewed by a human and cannot enter an execution flow.
 */
export function validateContentClaims(draft: ContentDraft, claims: readonly ProductClaim[]): ContentValidation {
  const approved = new Map(claims.filter(isApprovedClaim).map((claim) => [claim.id, claim]));
  const reasons: string[] = [];

  if (draft.citedClaimIds.length === 0) reasons.push("A content draft must cite approved claims before review.");
  for (const claimId of draft.citedClaimIds) {
    if (!approved.has(claimId)) reasons.push(`Claim ${claimId} is not currently approved with evidence.`);
  }
  return { valid: reasons.length === 0, reasons };
}

export function moveContentToReview(draft: ContentDraft, claims: readonly ProductClaim[]): ContentDraft {
  if (draft.status !== "draft" && draft.status !== "claim_validation") {
    throw new Error(`Content in ${draft.status} cannot enter review.`);
  }
  const validation = validateContentClaims(draft, claims);
  if (!validation.valid) throw new Error(validation.reasons.join(" "));
  return { ...draft, status: "review" };
}
